# Generated by Django 5.2.4 on 2025-07-14 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('weekday', models.CharField(editable=False, max_length=20)),
                ('sessions', models.IntegerField()),
                ('focused_time', models.IntegerField(help_text='Tempo de foco em minutos')),
                ('break_time', models.IntegerField(help_text='Tempo de descanso em minutos')),
                ('category', models.CharField(max_length=50)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
